image:
  name: star3am/repository:tools

stages:
  - main

master:
  stage: master
  script:
    # - pwd
    # - docker build -t tools:latest .
    # - docker images | grep tools
    # - docker buildx create --name tools --use
    # - docker buildx inspect
    # # https://vikaspogu.dev/posts/docker-buildx-setup/
    # - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    # - docker buildx build --platform=linux/amd64,linux/arm64 -t tools:latest .
    # - docker buildx imagetools inspect star3am/repository:tools
    - |
      docker compose run --rm tools bash -c '
      cd /app
      env | grep PATH
      cat /etc/lsb-release
      uname -a
      pwd
      tree -a -L 1
      echo "*** python -V"
      python -V
      echo "*** pip -V"
      pip -V
      echo "*** az --version"
      az --version
      echo "*** cookiecutter --version"
      cookiecutter --version
      echo "*** aws --version"
      aws --version
      echo "*** gcloud --version"
      gcloud --version
      echo "*** dbt --version"
      dbt --version
      echo "*** kubectl version"
      kubectl version
      echo "*** helm version"
      helm version
      echo "*** terraform -version"
      terraform -version
      echo "*** terragrunt -version"
      terragrunt -version
      echo "*** pre-commit --version"
      pre-commit --version
      echo "*** packer version"
      packer version
      # pre-commit validate-config
      # pre-commit run --all-files
      # echo "*** pip list"
      # pip list
      pwd'
  only:
    - main
