# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      exclude: .gitlab-ci.yml
      # exclude: |
      #           (?x)^(
      #               README.md|
      #               .gitlab-ci.yml
      #           )$
    - id: check-yaml
    - id: check-merge-conflict
    # BUG: Currently detects README.md as executable
    # - id: check-executables-have-shebangs
    - id: check-symlinks
    - id: check-json

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.74.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs

# - repo: https://github.com/jumanjihouse/pre-commit-hooks
#   rev: 2.1.6
#   hooks:
#     - id: shfmt
#       args: ['-l', '-i', '2', '-ci', '-sr', '-w']
#     - id: shellcheck

# Dockerfile linter
- repo: https://github.com/hadolint/hadolint
  rev: v2.10.0
  hooks:
    - id: hadolint
      args: [
        '--ignore', 'DL3027', # Do not use apt
        '--ignore', 'DL3007', # Using latest
        '--ignore', 'DL4006', # Not related to alpine
        '--ignore', 'SC1091', # Useless check
        '--ignore', 'SC2015', # Useless check
        '--ignore', 'SC3037', # Not related to alpine
        '--ignore', 'DL3013', # Pin versions in pip
        '--ignore', 'DL3003', # Ignore WORKSPACE to switch directory
        '--ignore', 'DL3008', # Pin versions in apt get install
        '--ignore', 'SC2155', # Declare and assign separately to avoid masking return values
        '--ignore', 'DL3059', # Multiple consecutive `RUN` instructions. Consider consolidation
        '--ignore', 'DL3009', # Delete the apt-get lists after installing something
        '--ignore', 'DL3015', # Avoid additional packages by specifying `--no-install-recommends`
      ]
